name: tests

on:
  pull_request:
  push:
    branches-ignore: [gh-pages]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion: [stable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nimversion }}
    - name: Test
      run: |
        nimble install
        nimble test
        nimble refresh
